// Code generated by goctl. DO NOT EDIT.
package types

type ChatRequest struct {
	UserId     uint   `header:"User-ID"`
	RoomNumber string `json:"roomNumber"`
	Content    string `json:"content"`
}

type ChatResponse struct {
}

type ChatWsRequest struct {
	UserId     uint   `header:"User-ID"`
	RoomNumber string `form:"roomNumber"`
}

type ChatWsResponse struct {
}

type GetGiftListRequest struct {
}

type GetGiftListResponse struct {
	Gifts []GiftItem
}

type GiftItem struct {
	Name  string `json:"name"`
	Price int    `json:"price"`
	Icon  string `json:"icon"`
}

type LotteryRequest struct {
	AnchorId      uint   `header:"User-ID"`
	Prize         string `json:"prize"`
	Count         uint   `json:"count"`
	LotteryMethod int    `json:"lotteryMethod"` // 0: 点击参与抽奖, 1: 发送弹幕抽奖, 2: 送礼物抽奖
	Duration      string `json:"duration"`
	StartTime     string `json:"startTime"`
}

type LotteryResponse struct {
}

type LotteryResultRequest struct {
	LotteryId uint `form:"lotteryId"`
}

type LotteryResultResponse struct {
	Winners []Winner `json:"winners"`
}

type ParticipateLotteryRequest struct {
	UserId     uint `header:"User-ID"`
	LotteryId  uint `json:"lotteryId"`
	MethodType int  `json:"methodType"` // 0: 点击参与抽奖, 1: 发送弹幕抽奖, 2: 送礼物抽奖
}

type ParticipateLotteryResponse struct {
}

type SendGiftRequest struct {
	UserID   uint `header:"User-ID"`
	AnchorID uint `json:"anchorId"`
	GiftID   uint `json:"giftId"`
	Count    uint `json:"count"`
}

type SendGiftResponse struct {
}

type Winner struct {
	UserId uint   `json:"userId"`
	Prize  string `json:"prize"`
}
