// Code generated by goctl. DO NOT EDIT.
package types

type ChatRequest struct {
	UserId     uint   `header:"User-ID"`
	RoomNumber string `form:"roomNumber"`
}

type ChatResponse struct {
}

type LotteryRequest struct {
	AnchorId      uint   `header:"User-ID"`
	Prize         string `json:"prize"`
	Count         uint   `json:"count"`
	LotteryMethod int    `json:"lotteryMethod"` // 0: 点击参与抽奖, 1: 发送弹幕抽奖, 2: 送礼物抽奖
	Duration      string `json:"duration"`
	StartTime     string `json:"startTime"`
}

type LotteryResponse struct {
}

type LotteryResultRequest struct {
	LotteryId uint `form:"lotteryId"`
}

type LotteryResultResponse struct {
	Winners []Winner `json:"winners"`
}

type ParticipateLotteryRequest struct {
	UserId     uint `header:"User-ID"`
	LotteryId  uint `json:"lotteryId"`
	MethodType int  `json:"methodType"` // 0: 点击参与抽奖, 1: 发送弹幕抽奖, 2: 送礼物抽奖
}

type ParticipateLotteryResponse struct {
}

type Winner struct {
	UserId uint   `json:"userId"`
	Prize  string `json:"prize"`
}
