// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"live/servers/log_server/log_api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/log/log",
				Handler: logListHandler(serverCtx),
			},
		},
	)
}
