// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"live/servers/user_sever/user_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/follow",
				Handler: followHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/info",
				Handler: userInfoHandler(serverCtx),
			},
		},
	)
}
