// Code generated by goctl. DO NOT EDIT.
package types

type AnchorItem struct {
	AnchorID int
	Fans     int
}

type GetAnchorFansRankRequest struct {
	TopN int64 `form:"topN"`
}

type GetAnchorFansRankResponse struct {
	Ranks []AnchorItem
}

type GetGiftRequest struct {
	TopN int64 `form:"topN"`
}

type GetGiftResponse struct {
	Ranks []GiftItem
}

type GetRoomRankRequest struct {
	TopN int64 `form:"topN"`
}

type GetRoomRankResponse struct {
	Ranks []RoomItem
}

type GiftItem struct {
	AnchorID int
	Count    int // 礼物价值
}

type RankItem struct {
	RoomRank   []RoomItem
	AnchorRank []AnchorItem
	GiftRank   []GiftItem
}

type RoomItem struct {
	RoomID   string
	Audience int
}
