// Code generated by goctl. DO NOT EDIT.
package types

type AnchorItem struct {
	AnchorID string
	Fans     int
}

type GetAnchorFansRankRequest struct {
	TopN int64 `form:"topN"`
}

type GetAnchorFansRankResponse struct {
	Ranks []AnchorItem
}

type GetRoomRankRequest struct {
	TopN int64 `form:"topN"`
}

type GetRoomRankResponse struct {
	Ranks []RoomItem
}

type RankItem struct {
	RoomRank   []RoomItem
	AnchorRank []AnchorItem
}

type RoomItem struct {
	RoomID   string
	Audience int
}
