// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"live/interact_server/interact_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/interact/chat/ws",
				Handler: chatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/interact/lottery",
				Handler: lotteryDrawHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/interact/lottery/participate",
				Handler: participateLotteryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/interact/lottery/result",
				Handler: lotteryResultHandler(serverCtx),
			},
		},
	)
}
