// Code generated by goctl. DO NOT EDIT.
package types

type ConferenceRequest struct {
	RoomNumber string `form:"roomNumber"` //直播间号
	UserID     uint   `header:"User-ID"`  //用户ID
}

type ConferenceRespones struct {
}

type CreateRequest struct {
	AnchorID    uint   `header:"User-ID"`       //主播ID
	Title       string `json:"title"`           //标题
	Description string `json:"description"`     //直播间描述
	Avatar      string `json:"avatar,optional"` //封面
}

type CreateResponse struct {
	RoomNumber   string `json:"roomNumber"`   //直播间号
	RTMPEndpoint string `json:"rtmpEndpoint"` //RTMP推流地址
	CreateAt     string `json:"createAt"`     //创建时间
}

type EndRequest struct {
	RoomNumber string `json:"roomNumber"` //直播间号
	AnchorID   uint   `header:"User-ID"`  //主播ID
}

type EndResponse struct {
}

type EnterRequest struct {
	RoomNumber string `json:"roomNumber"` //直播间号
	UserID     uint   `header:"User-ID"`  //用户ID
}

type EnterResponse struct {
	LiveMessage LiveMessage `json:"liveMessage"` //直播间信息
	RTMPAddress string      `json:"rtmpAddress"` //RTMP播放地址
}

type ExitRequest struct {
	RoomNumber string `json:"roomNumber"` //直播间号
	UserID     uint   `json:"userId"`     //用户ID
}

type ExitResponse struct {
}

type ListMessage struct {
	LiveMessages []LiveMessage `json:"liveMessages"` //直播间列表
}

type LiveMessage struct {
	Title       string `json:"title"`       //标题
	Description string `json:"description"` //直播间描述
	OnlineUsers int    `json:"onlineUsers"` //在线用户数
	RoomNumber  string `json:"roomNumber"`  //直播间号
}

type PeopleRequest struct {
	RoomNumber string `form:"roomNumber"` //直播间号
	UserID     uint   `header:"User-ID"`  //用户ID
}

type PeopleRespones struct {
}
