// Code generated by goctl. DO NOT EDIT.
package types

type FollowRequest struct {
	UserID   uint `header:"User-ID"`
	AnchorId uint `json:"anchorId"`
}

type FollowResponse struct {
}

type UserInfoRequest struct {
	UserID uint `header:"User-ID"`
}

type UserInfoResponse struct {
	Username string `json:"username"`
	Balance  int    `json:"balance"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Fans     int    `json:"fans"`
}
