// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoRequest struct {
	UserID uint `header:"User-ID"`
}

type UserInfoResponse struct {
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Fans     int    `json:"fans"`
}
